### ISSUE TITLE
Possible bug searching "map/"

### ISSUE THREAD

**Issue by axelson** [rowlandcodes/exhelp#1]
Hi! Thanks for this project, I think I'll be able to get some good use out of it :tada: 

I think I may have stumbled upon a bug. First I ran `exh -s "map"` and decided that there were too many results, so I wanted to narrow the results down to all the functions that end in `map` so I searched for `map/` with the idea that it would return results like `:orddict.map/2` and not results like `:erts_internal.map_next/3`. But instead I got an error:
```
jason@frame ~/config (master) [1]> exh -s "map/"
** (TokenMissingError) nofile:1:4: syntax error: expression is incomplete
    |
  1 | map/
    |    ^
    (exhelp 0.3.0) lib/exhelp.ex:9: Exhelp.decompose/1
    (exhelp 0.3.0) lib/exhelp.ex:41: Exhelp.execute/2
    (elixir 1.13.4) lib/kernel/cli.ex:126: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

Is this a bug? Perhaps there's some other way to accomplish what I'm trying to do?

**Comment by rowlandcodes** [comment]
Thanks for giving it a try.

There is a bug here in that Exhelp is not returning a user friendly error.
And because I'm potentially violating the principle of least surprise.

Exhelp is trying to turn `map/` into an Module, Function, and Arity to know which kind of search to use.
Since `map/` isn't a valid form for an MFA, 
It throws the syntax error while trying to parse it as one.

The search logic itself is a basic `String.starts_with` compared directly against the list of function atoms.
It doesn't compare the input string against a stringified `Module.fun/arity` which is why it fails here.

My idea was that any query requiring more complexity than starts_with would be delegated to other unix programs.

For example, this should get the results you were looking for:
```
exh -s map | grep 'map/'
```

**Comment by rowlandcodes** [comment]
That said, there doesn't seem be a significant performance difference between the bespoke MFA logic and `--all-functions`,
So I'm going to see if I can simplify `Exhelp.Search` by directly passing the input string,
And filtering on `String.contains?(input)` on the formatted `"Module.fun/arity"`.

If my theory is correct, this command would give your desired output:
```
exh -s .map/
```

Since `exh -s map/` would still return functions like `:lists.flatmap/2` that do contain that substring.
The downside to this approach is that a query like `exh -s lists` would return both functions and modules that contain that substring:

```
$ exh -s lists
:dets_utils.get_freelists/1
...
:lists.zip/2
```

**Comment by axelson** [comment]
Ah, I see. Changing `--search` to search on `--all-functions` by default makes sense to me (as a user). But maybe that means there could be an additional operation `--structured-search` that would do the `MFA` search (since I could see that being useful as well).

**Comment by rowlandcodes** [comment]
I've changed `--search` to search on `--all-functions` for non-module queries with #5.
I've decided to avoid `--structured-search` since it allows me to remove the vendored `Decompose` module.

**Comment by axelson** [comment]
Great, thanks!
